# Generated by Django 3.0.1 on 2020-12-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/Profile.jpg', null=True, upload_to='profile'),
        ),
    ]
